version: "3.8"

services:
  bookstore_app:
    container_name: bookstore_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - appvolume:/app
    ports:
      - "3000:3000"
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - bookstorenetwork

  postgresdb:
    container_name: postgresdb
    image: postgres:16-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qweasd
    volumes:
      - postgresvolume:/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/create-database-bookstore.sql
    ports:
      - '5433:5432'
    networks:
      - bookstorenetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bookstorenetwork:

volumes:
  postgresvolume:
  appvolume:
