export const BOOKS = [
  {
    id: 'e05b26a4-36fe-4f67-8c7b-922676030f07',
    title: 'Atomic Habits',
    synopsis: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones',
    author: 'James Clear',
    publisher: 'Avery',
    publish_date: '2018',
    pages: 320,
    quantity: 50,
    price: 14.99,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-4.jpg'
  },
  {
    id: 'f9e27e4e-2cbe-49c9-a58e-020f883d5a80',
    title: 'The Subtle Art of Not Giving a F*ck',
    synopsis: 'A Counterintuitive Approach to Living a Good Life',
    author: 'Mark Manson',
    publisher: 'HarperOne',
    publish_date: '2016',
    pages: 272,
    quantity: 40,
    price: 14.34,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-5.jpg'
  },
  {
    id: '1c543f96-33e8-405d-97b4-4cd2ac25e91a',
    title: 'Rich Dad Poor Dad',
    synopsis: 'What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!',
    author: 'Robert T. Kiyosaki',
    publisher: 'Plata',
    publish_date: '2022',
    pages: 336,
    quantity: 45,
    price: 6.39,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-3.jpg'
  },
  {
    id: '9d95bc0b-5054-40c5-9276-998723c6c5c2',
    title: 'Can\'t Hurt Me',
    synopsis: 'Master Your Mind and Defy the Odds',
    author: 'David Goggins',
    publisher: 'Lioncrest',
    publish_date: '2020',
    pages: 364,
    quantity: 65,
    price: 26.99,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-2.jpg'
  },
  {
    id: 'd8fabbd4-74c0-457a-ae41-c8f136f677bb',
    title: 'How to Know a Person',
    synopsis: 'The Art of Seeing Others Deeply and Being Deeply Seen',
    author: 'David Brooks',
    publisher: 'Random House',
    publish_date: '2023',
    pages: 320,
    quantity: 60,
    price: 18.92,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-1.jpg'
  },
  {
    id: '5034ce4e-3b5d-474f-9fcc-892ac9d66ad9',
    title: 'The Social Animal',
    synopsis: 'The Hidden Sources of Love, Character, and Achievement',
    author: 'David Brooks',
    publisher: 'Random House',
    publish_date: '2012',
    pages: 448,
    quantity: 60,
    price: 25.60,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-6.jpg'
  },
  {
    id: 'ee2fbe6d-0355-4329-a911-567cd7f2e753',
    title: 'The Power of Discipline',
    synopsis: 'How to Use Self Control and Mental Toughness to Achieve Your Goals',
    author: 'Daniel Walter',
    publisher: 'Independently',
    publish_date: '2020',
    pages: 132,
    quantity: 30,
    price: 22.49,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-7.jpg'
  },
  {
    id: '1ce82dda-6aa8-4935-9016-9ee370598f27',
    title: 'Mind Management, Not Time Management',
    synopsis: 'Productivity When Creativity Matters (Getting Art Done)',
    author: 'David Kadavy',
    publisher: 'Kadavy, Inc',
    publish_date: '2020',
    pages: 262,
    quantity: 35,
    price: 35.38,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-8.jpg'
  },
  {
    id: '70bd52b7-4074-4293-acc0-4dfa7728c565',
    title: 'Finish What You Start',
    synopsis: 'The Art of Following Through, Taking Action, Executing, & Self-Discipline (Live a Disciplined Life)',
    author: 'Peter Hollins',
    publisher: 'CreateSpace',
    publish_date: '2018',
    pages: 206,
    quantity: 35,
    price: 25.99,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-9.jpg'
  },
  {
    id: '7a52afab-5a4c-4f20-a16b-cf16f3707660',
    title: 'Meditations',
    synopsis: 'Adapted for the Contemporary Reader',
    author: 'Marcus Aurelius',
    publisher: 'CreateSpace',
    publish_date: '2016',
    pages: 211,
    quantity: 40,
    price: 26.99,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-10.jpg'
  },
  {
    id: '28c21c1c-a656-4c5a-9093-19cd71ab31d9',
    title: 'The 48 Laws of Power',
    synopsis: 'Gain Power, Observe Power, Defend Against Power',
    author: 'Robert Greene',
    publisher: 'Penguin Books',
    publish_date: '2000',
    pages: 452,
    quantity: 40,
    price: 32.49,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-11.jpg'
  },
  {
    id: '9e926b3d-a9d0-456d-8aa0-94355f50ef0d',
    title: 'Stoicism for New Life',
    synopsis: 'The Path to a Stoic Mindset for Emotional Resilience and Joy',
    author: 'Michael Whiteclear',
    publisher: 'Independently',
    publish_date: '2023',
    pages: 170,
    quantity: 40,
    price: 18.99,
    cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-12.jpg'
  }
]
