export const ORDERS = [
  {
    buyer_id: "06028e2c-dfe3-45e7-96ea-c781c5eff70b",
    buyer_name: "Mark Zuck",
    buyer_email: "mark@gmail.com",
    shipping_name: "Mark Zuckerberg",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 6,
    total_amount: 64.14,
    order_items: [
      {
        book_id: 'e05b26a4-36fe-4f67-8c7b-922676030f07',
        book_title: 'Atomic Habits',
        book_synopsis: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones',
        book_author: 'James Clear',
        book_publisher: 'Avery',
        book_publish_date: '2018',
        book_pages: 320,
        book_price: 14.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-4.jpg',
        quantity: 3,
        total_amount: 44.97,
      },
      {
        book_id: '1c543f96-33e8-405d-97b4-4cd2ac25e91a',
        book_title: 'Rich Dad Poor Dad',
        book_synopsis: 'What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!',
        book_author: 'Robert T. Kiyosaki',
        book_publisher: 'Plata',
        book_publish_date: '2022',
        book_pages: 336,
        book_price: 6.39,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-3.jpg',
        quantity: 3,
        total_amount: 19.17,
      }
    ]
  },
  {
    buyer_id: "06028e2c-dfe3-45e7-96ea-c781c5eff70b",
    buyer_name: "Mark Zuck",
    buyer_email: "mark@gmail.com",
    shipping_name: "Mark Zuckerberg",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 2,
    total_amount: 37.98,
    order_items: [
      {
        book_id: '9e926b3d-a9d0-456d-8aa0-94355f50ef0d',
        book_title: 'Stoicism for New Life',
        book_synopsis: 'The Path to a Stoic Mindset for Emotional Resilience and Joy',
        book_author: 'Michael Whiteclear',
        book_publisher: 'Independently',
        book_publish_date: '2023',
        book_pages: 170,
        book_price: 18.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-12.jpg',
        quantity: 2,
        total_amount: 37.98,
      }
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 14.34,
    order_items: [
      {
        book_id: 'f9e27e4e-2cbe-49c9-a58e-020f883d5a80',
        book_title: 'The Subtle Art of Not Giving a F*ck',
        book_synopsis: 'A Counterintuitive Approach to Living a Good Life',
        book_author: 'Mark Manson',
        book_publisher: 'HarperOne',
        book_publish_date: '2016',
        book_pages: 272,
        book_price: 14.34,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-5.jpg',
        quantity: 1,
        total_amount: 14.34,
      }
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 22.49,
    order_items: [
      {
        book_id: 'ee2fbe6d-0355-4329-a911-567cd7f2e753',
        book_title: 'The Power of Discipline',
        book_synopsis: 'How to Use Self Control and Mental Toughness to Achieve Your Goals',
        book_author: 'Daniel Walter',
        book_publisher: 'Independently',
        book_publish_date: '2020',
        book_pages: 132,
        book_price: 22.49,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-7.jpg',
        quantity: 1,
        total_amount: 22.49,
      }
    ]
  },
  {
    buyer_id: "06028e2c-dfe3-45e7-96ea-c781c5eff70b",
    buyer_name: "Mark Zuck",
    buyer_email: "mark@gmail.com",
    shipping_name: "Mark Zuckerberg",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 5,
    total_amount: 162.45,
    order_items: [
      {
        book_id: '28c21c1c-a656-4c5a-9093-19cd71ab31d9',
        book_title: 'The 48 Laws of Power',
        book_synopsis: 'Gain Power, Observe Power, Defend Against Power',
        book_author: 'Robert Greene',
        book_publisher: 'Penguin Books',
        book_publish_date: '2000',
        book_pages: 452,
        book_price: 32.49,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-11.jpg',
        quantity: 5,
        total_amount: 162.45,
      }
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 5,
    total_amount: 64.05,
    order_items: [
      {
        book_id: 'e05b26a4-36fe-4f67-8c7b-922676030f07',
        book_title: 'Atomic Habits',
        book_synopsis: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones',
        book_author: 'James Clear',
        book_publisher: 'Avery',
        book_publish_date: '2018',
        book_pages: 320,
        book_price: 14.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-4.jpg',
        quantity: 2,
        total_amount: 29.98,
      },
      {
        book_id: 'f9e27e4e-2cbe-49c9-a58e-020f883d5a80',
        book_title: 'The Subtle Art of Not Giving a F*ck',
        book_synopsis: 'A Counterintuitive Approach to Living a Good Life',
        book_author: 'Mark Manson',
        book_publisher: 'HarperOne',
        book_publish_date: '2016',
        book_pages: 272,
        book_price: 14.34,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-5.jpg',
        quantity: 2,
        total_amount: 28.68,
      },
      {
        book_id: '1c543f96-33e8-405d-97b4-4cd2ac25e91a',
        book_title: 'Rich Dad Poor Dad',
        book_synopsis: 'What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!',
        book_author: 'Robert T. Kiyosaki',
        book_publisher: 'Plata',
        book_publish_date: '2022',
        book_pages: 336,
        book_price: 6.39,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-3.jpg',
        quantity: 1,
        total_amount: 6.39,
      },
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 2,
    total_amount: 70.76,
    order_items: [
      {
        book_id: '1ce82dda-6aa8-4935-9016-9ee370598f27',
        book_title: 'Mind Management, Not Time Management',
        book_synopsis: 'Productivity When Creativity Matters (Getting Art Done)',
        book_author: 'David Kadavy',
        book_publisher: 'Kadavy, Inc',
        book_publish_date: '2020',
        book_pages: 262,
        book_price: 35.38,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-8.jpg',
        quantity: 2,
        total_amount: 70.76,
      },
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 4,
    total_amount: 129.96,
    order_items: [
      {
        book_id: '28c21c1c-a656-4c5a-9093-19cd71ab31d9',
        book_title: 'The 48 Laws of Power',
        book_synopsis: 'Gain Power, Observe Power, Defend Against Power',
        book_author: 'Robert Greene',
        book_publisher: 'Penguin Books',
        book_publish_date: '2000',
        book_pages: 452,
        book_price: 32.49,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-11.jpg',
        quantity: 4,
        total_amount: 129.96,
      },
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 2,
    total_amount: 45.98,
    order_items: [
      {
        book_id: '7a52afab-5a4c-4f20-a16b-cf16f3707660',
        book_title: 'Meditations',
        book_synopsis: 'Adapted for the Contemporary Reader',
        book_author: 'Marcus Aurelius',
        book_publisher: 'CreateSpace',
        book_publish_date: '2016',
        book_pages: 211,
        book_price: 26.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-10.jpg',
        quantity: 1,
        total_amount: 26.99,
      },
      {
        book_id: '9e926b3d-a9d0-456d-8aa0-94355f50ef0d',
        book_title: 'Stoicism for New Life',
        book_synopsis: 'The Path to a Stoic Mindset for Emotional Resilience and Joy',
        book_author: 'Michael Whiteclear',
        book_publisher: 'Independently',
        book_publish_date: '2023',
        book_pages: 170,
        book_price: 18.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-12.jpg',
        quantity: 1,
        total_amount: 18.99,
      }
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 26.99,
    order_items: [
      {
        book_id: '9d95bc0b-5054-40c5-9276-998723c6c5c2',
        book_title: 'Can\'t Hurt Me',
        book_synopsis: 'Master Your Mind and Defy the Odds',
        book_author: 'David Goggins',
        book_publisher: 'Lioncrest',
        book_publish_date: '2020',
        book_pages: 364,
        book_price: 26.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-2.jpg',
        quantity: 1,
        total_amount: 26.99,
      }
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 18.92,
    order_items: [
      {
        book_id: 'd8fabbd4-74c0-457a-ae41-c8f136f677bb',
        book_title: 'How to Know a Person',
        book_synopsis: 'The Art of Seeing Others Deeply and Being Deeply Seen',
        book_author: 'David Brooks',
        book_publisher: 'Random House',
        book_publish_date: '2023',
        book_pages: 320,
        book_price: 18.92,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-1.jpg',
        quantity: 1,
        total_amount: 18.92,
      }
    ]
  },
  {
    buyer_id: "06028e2c-dfe3-45e7-96ea-c781c5eff70b",
    buyer_name: "Mark Zuck",
    buyer_email: "mark@gmail.com",
    shipping_name: "Mark Zuckerberg",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 26.99,
    order_items: [
      {
        book_id: '9d95bc0b-5054-40c5-9276-998723c6c5c2',
        book_title: 'Can\'t Hurt Me',
        book_synopsis: 'Master Your Mind and Defy the Odds',
        book_author: 'David Goggins',
        book_publisher: 'Lioncrest',
        book_publish_date: '2020',
        book_pages: 364,
        book_price: 26.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-2.jpg',
        quantity: 1,
        total_amount: 26.99,
      }
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 25.60,
    order_items: [
      {
        book_id: '5034ce4e-3b5d-474f-9fcc-892ac9d66ad9',
        book_title: 'The Social Animal',
        book_synopsis: 'The Hidden Sources of Love, Character, and Achievement',
        book_author: 'David Brooks',
        book_publisher: 'Random House',
        book_publish_date: '2012',
        book_pages: 448,
        book_price: 25.60,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-6.jpg',
        quantity: 1,
        total_amount: 25.60,
      }
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 25.99,
    order_items: [
      {
        book_id: '70bd52b7-4074-4293-acc0-4dfa7728c565',
        book_title: 'Finish What You Start',
        book_synopsis: 'The Art of Following Through, Taking Action, Executing, & Self-Discipline (Live a Disciplined Life)',
        book_author: 'Peter Hollins',
        book_publisher: 'CreateSpace',
        book_publish_date: '2018',
        book_pages: 206,
        book_price: 25.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-9.jpg',
        quantity: 1,
        total_amount: 25.99,
      }
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 32.49,
    order_items: [
      {
        book_id: '28c21c1c-a656-4c5a-9093-19cd71ab31d9',
        book_title: 'The 48 Laws of Power',
        book_synopsis: 'Gain Power, Observe Power, Defend Against Power',
        book_author: 'Robert Greene',
        book_publisher: 'Penguin Books',
        book_publish_date: '2000',
        book_pages: 452,
        book_price: 32.49,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-11.jpg',
        quantity: 1,
        total_amount: 32.49,
      }
    ]
  },
  {
    buyer_id: "06028e2c-dfe3-45e7-96ea-c781c5eff70b",
    buyer_name: "Mark Zuck",
    buyer_email: "mark@gmail.com",
    shipping_name: "Mark Zuckerberg",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 25.99,
    order_items: [
      {
        book_id: '70bd52b7-4074-4293-acc0-4dfa7728c565',
        book_title: 'Finish What You Start',
        book_synopsis: 'The Art of Following Through, Taking Action, Executing, & Self-Discipline (Live a Disciplined Life)',
        book_author: 'Peter Hollins',
        book_publisher: 'CreateSpace',
        book_publish_date: '2018',
        book_pages: 206,
        book_price: 25.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-9.jpg',
        quantity: 1,
        total_amount: 25.99,
      }
    ]
  },
  {
    buyer_id: "a34242ad-07a3-4a59-8703-30d1a49210c3",
    buyer_name: "John Doe",
    buyer_email: "john@gmail.com",
    shipping_name: "John Doe",
    shipping_phone: "+628132133212",
    shipping_address: "Jl. Kalibata Utara II, Kalibata, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12740",
    total_quantity: 1,
    total_amount: 14.99,
    order_items: [
      {
        book_id: 'e05b26a4-36fe-4f67-8c7b-922676030f07',
        book_title: 'Atomic Habits',
        book_synopsis: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones',
        book_author: 'James Clear',
        book_publisher: 'Avery',
        book_publish_date: '2018',
        book_pages: 320,
        book_price: 14.99,
        book_cover_image: 'https://res.cloudinary.com/novalyezu/image/upload/bookstore/books/sample-4.jpg',
        quantity: 1,
        total_amount: 14.99,
      }
    ]
  },
]